#!/usr/bin/python
# -*- coding: utf-8 -*-
#
# (c) 2018, Ricardo Carrillo Cruz <ricarril@redhat.com>
# (c) 2018, Yanis Guenane <yguenane@redhat.com>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

---
- name: Create SSH key
  digital_ocean_sshkey:
    name: '{{ cloud_sshkey_name }}'
    ssh_pub_key: '{{ cloud_sshkey_content }}'
