---
- name: Manage SSH key
  os_keypair:
    name: '{{ cloud_sshkey_name }}'
    public_key: '{{ cloud_sshkey_content }}'
    region_name: '{{ cloud_sshkey_region|default(None) }}'
    state: '{{ cloud_sshkey_state|default("present") }}'
